### ISSUE TITLE
Problem with UtaiteDB

### ISSUE THREAD

**Issue by amogus07** [prTopi/beets-vocadb#3] opened 2024-07-18 16:27 UTC
As you might have noticed, I created a fork of this plugin that uses UtaiteDB instead of VocaDB. However, it doesn't seem to handle the albumartist tag correctly. In the list of candidates, it appears to be blank. When I save an album to my library, it sets the albumartist tag of each song to the artist tag of the first song. Can you reproduce this behavior with my fork? Do you have any idea how to fix this since you are more familiar with the code?

**Comment by prTopi** [comment] 2024-07-18 19:56
Tried a few albums but couldn't reproduce on your fork. I don't have any albums that would match on UtaiteDB, but used the search function on beets and it worked for me.

Does this happen on specific albums or all of them? If it's specific albums could you give me the album ids so I can test them myself.

And are you using latest beets release (2.0.0)? This plugin uses the newer `albumartists` tag that's not in older versions and I'm not sure how well it works on them.

**Comment by amogus07** [comment] 2024-07-18 20:22
https://utaitedb.net/Al/1106

**Comment by prTopi** [comment] 2024-07-18 23:07
Fixed in 1baa6b0

UtaiteDB seems to have a different way on how artists are tagged, and don't add always add producers while tagging artists. I added a quick and dirty fix to use vocalists as producers if no producers are found, since all UtaiteDB albums seem to have vocalists.

**Closed by prTopi** 2024-07-18 23:07 UTC
